version: "3.8"

services:
  messaging-service:
    container_name: messaging-service
    build: .
    command: npm start
    volumes:
      - .:/usr/armut/messaging-service/
      - /usr/armut/messaging-service/node_modules
    ports:
      - 3003:3000
    depends_on:
      - mongo
    environment:
      PORT: 3000
      DATABASE_URL: mongodb://berkant:armut@mongo:27017/MessagingService
  mongo:
    image: mongo:4.4.6
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: armut
